export default {
  0: {
    'a_star': [
      { type: 'visit', square: [ 1, 3 ] },
      { type: 'visit', square: [ 1, 4 ] },
      { type: 'visit', square: [ 1, 5 ] },
      { type: 'visit', square: [ 1, 6 ] },
      { type: 'visit', square: [ 2, 6 ] },
      { type: 'visit', square: [ 3, 6 ] },
      { type: 'visit', square: [ 4, 6 ] },
      { type: 'visit', square: [ 5, 6 ] },
      { type: 'visit', square: [ 6, 6 ] },
      { type: 'visit', square: [ 5, 5 ] },
      { type: 'visit', square: [ 5, 7 ] },
      { type: 'visit', square: [ 7, 6 ] },
      { type: 'visit', square: [ 8, 6 ] },
      { type: 'visit', square: [ 5, 8 ] },
      { type: 'visit', square: [ 5, 4 ] },
      { type: 'visit', square: [ 9, 6 ] },
      { type: 'visit', square: [ 8, 5 ] },
      { type: 'visit', square: [ 10, 6 ] },
      { type: 'visit', square: [ 5, 9 ] },
      { type: 'visit', square: [ 6, 9 ] },
      { type: 'visit', square: [ 7, 9 ] },
      { type: 'visit', square: [ 8, 9 ] },
      { type: 'visit', square: [ 8, 10 ] },
      { type: 'visit', square: [ 8, 11 ] },
      { type: 'visit', square: [ 8, 12 ] },
      { type: 'visit', square: [ 9, 12 ] },
      { type: 'visit', square: [ 10, 12 ] },
      { type: 'visit', square: [ 11, 12 ] },
      { type: 'visit', square: [ 11, 11 ] },
      { type: 'visit', square: [ 11, 10 ] },
      { type: 'visit', square: [ 11, 9 ] },
      { type: 'visit', square: [ 12, 9 ] },
      { type: 'visit', square: [ 13, 9 ] },
      { type: 'visit', square: [ 11, 13 ] },
      { type: 'visit', square: [ 14, 9 ] },
      { type: 'visit', square: [ 11, 14 ] },
      { type: 'visit', square: [ 15, 9 ] },
      { type: 'visit', square: [ 14, 8 ] },
      { type: 'visit', square: [ 11, 6 ] },
      { type: 'visit', square: [ 5, 3 ] },
      { type: 'visit', square: [ 16, 9 ] },
      { type: 'visit', square: [ 11, 15 ] },
      { type: 'visit', square: [ 5, 10 ] },
      { type: 'visit', square: [ 8, 4 ] },
      { type: 'visit', square: [ 12, 6 ] },
      { type: 'visit', square: [ 17, 9 ] },
      { type: 'visit', square: [ 17, 10 ] },
      { type: 'visit', square: [ 17, 11 ] },
      { type: 'visit', square: [ 17, 12 ] },
      { type: 'visit', square: [ 17, 13 ] },
      { type: 'visit', square: [ 17, 14 ] },
      { type: 'visit', square: [ 17, 15 ] },
      { type: 'visit', square: [ 17, 16 ] },
      { type: 'visit', square: [ 17, 17 ] },
      { type: 'visit', square: [ 17, 18 ] },
      { type: 'visit', square: [ 18, 18 ] },
      { type: 'visit', square: [ 19, 18 ] },
      { type: 'visit', square: [ 20, 18 ] },
      { type: 'visit', square: [ 20, 17 ] },
      { type: 'visit', square: [ 20, 16 ] },
      { type: 'visit', square: [ 20, 15 ] },
      { type: 'visit', square: [ 21, 15 ] },
      { type: 'visit', square: [ 20, 19 ] },
      { type: 'visit', square: [ 22, 15 ] },
      { type: 'visit', square: [ 20, 20 ] },
      { type: 'visit', square: [ 23, 15 ] },
      { type: 'visit', square: [ 23, 16 ] },
      { type: 'visit', square: [ 23, 17 ] },
      { type: 'visit', square: [ 23, 18 ] },
      { type: 'visit', square: [ 23, 19 ] },
      { type: 'visit', square: [ 23, 20 ] },
      { type: 'visit', square: [ 24, 18 ] },
      { type: 'visit', square: [ 25, 18 ] },
      { type: 'visit', square: [ 23, 21 ] },
      { type: 'visit', square: [ 24, 21 ] },
      { type: 'visit', square: [ 25, 21 ] },
      { type: 'visit', square: [ 26, 21 ] },
      { type: 'visit', square: [ 26, 22 ] },
      { type: 'visit', square: [ 22, 21 ] },
      { type: 'visit', square: [ 26, 18 ] },
      { type: 'visit', square: [ 26, 23 ] },
      { type: 'visit', square: [ 16, 18 ] },
      { type: 'visit', square: [ 21, 21 ] },
      { type: 'visit', square: [ 26, 17 ] },
      { type: 'visit', square: [ 15, 18 ] },
      { type: 'visit', square: [ 20, 21 ] },
      { type: 'visit', square: [ 23, 14 ] },
      { type: 'visit', square: [ 14, 7 ] },
      { type: 'visit', square: [ 10, 15 ] },
      { type: 'visit', square: [ 19, 21 ] },
      { type: 'visit', square: [ 14, 18 ] },
      { type: 'visit', square: [ 11, 16 ] },
      { type: 'visit', square: [ 13, 6 ] },
      { type: 'visit', square: [ 5, 11 ] },
      { type: 'visit', square: [ 26, 16 ] },
      { type: 'visit', square: [ 26, 24 ] },
      { type: 'visit', square: [ 23, 13 ] },
      { type: 'visit', square: [ 18, 9 ] },
      { type: 'visit', square: [ 20, 22 ] },
      { type: 'visit', square: [ 18, 21 ] },
      { type: 'visit', square: [ 9, 15 ] },
      { type: 'visit', square: [ 13, 18 ] },
      { type: 'visit', square: [ 1, 2 ] },
      { type: 'visit', square: [ 8, 3 ] },
      { type: 'visit', square: [ 14, 6 ] },
      { type: 'visit', square: [ 5, 2 ] },
      { type: 'visit', square: [ 25, 24 ] },
      { type: 'visit', square: [ 14, 19 ] },
      { type: 'visit', square: [ 19, 9 ] },
      { type: 'visit', square: [ 11, 17 ] },
      { type: 'visit', square: [ 24, 24 ] },
      { type: 'visit', square: [ 17, 21 ] },
      { type: 'visit', square: [ 1, 7 ] },
      { type: 'visit', square: [ 5, 12 ] },
      { type: 'visit', square: [ 26, 15 ] },
      { type: 'visit', square: [ 23, 12 ] },
      { type: 'visit', square: [ 22, 12 ] },
      { type: 'visit', square: [ 21, 12 ] },
      { type: 'visit', square: [ 20, 12 ] },
      { type: 'visit', square: [ 20, 11 ] },
      { type: 'visit', square: [ 20, 10 ] },
      { type: 'visit', square: [ 12, 18 ] },
      { type: 'visit', square: [ 15, 6 ] },
      { type: 'visit', square: [ 8, 15 ] },
      { type: 'visit', square: [ 23, 24 ] },
      { type: 'visit', square: [ 20, 9 ] },
      { type: 'visit', square: [ 14, 5 ] },
      { type: 'visit', square: [ 16, 21 ] },
      { type: 'visit', square: [ 20, 23 ] },
      { type: 'visit', square: [ 14, 20 ] },
      { type: 'visit', square: [ 16, 6 ] },
      { type: 'visit', square: [ 11, 18 ] },
      { type: 'visit', square: [ 1, 8 ] },
      { type: 'visit', square: [ 8, 2 ] },
      { type: 'visit', square: [ 5, 13 ] },
      { type: 'visit', square: [ 4, 12 ] },
      { type: 'visit', square: [ 23, 11 ] },
      { type: 'visit', square: [ 27, 15 ] },
      { type: 'visit', square: [ 8, 16 ] },
      { type: 'visit', square: [ 26, 25 ] },
      { type: 'visit', square: [ 15, 21 ] },
      { type: 'visit', square: [ 5, 1 ] },
      { type: 'visit', square: [ 4, 1 ] },
      { type: 'visit', square: [ 3, 1 ] },
      { type: 'visit', square: [ 2, 1 ] },
      { type: 'visit', square: [ 17, 6 ] },
      { type: 'visit', square: [ 20, 8 ] },
      { type: 'visit', square: [ 14, 4 ] },
      { type: 'visit', square: [ 1, 9 ] },
      { type: 'visit', square: [ 14, 21 ] },
      { type: 'visit', square: [ 5, 14 ] },
      { type: 'visit', square: [ 20, 24 ] },
      { type: 'visit', square: [ 23, 10 ] },
      { type: 'visit', square: [ 23, 25 ] },
      { type: 'visit', square: [ 3, 12 ] },
      { type: 'visit', square: [ 8, 17 ] },
      { type: 'visit', square: [ 18, 6 ] },
      { type: 'visit', square: [ 28, 15 ] },
      { type: 'visit', square: [ 1, 1 ] },
      { type: 'visit', square: [ 8, 1 ] },
      { type: 'visit', square: [ 13, 21 ] },
      { type: 'visit', square: [ 20, 7 ] },
      { type: 'visit', square: [ 1, 10 ] },
      { type: 'visit', square: [ 5, 15 ] },
      { type: 'visit', square: [ 19, 6 ] },
      { type: 'visit', square: [ 14, 3 ] },
      { type: 'visit', square: [ 23, 9 ] },
      { type: 'visit', square: [ 14, 22 ] },
      { type: 'visit', square: [ 8, 18 ] },
      { type: 'visit', square: [ 2, 12 ] },
      { type: 'visit', square: [ 12, 21 ] },
      { type: 'visit', square: [ 26, 26 ] },
      { type: 'visit', square: [ 20, 25 ] },
      { type: 'visit', square: [ 27, 26 ] },
      { type: 'visit', square: [ 1, 11 ] },
      { type: 'visit', square: [ 29, 15 ] },
      { type: 'visit', square: [ 29, 16 ] },
      { type: 'visit', square: [ 29, 17 ] },
      { type: 'visit', square: [ 29, 18 ] },
      { type: 'visit', square: [ 29, 19 ] },
      { type: 'visit', square: [ 29, 20 ] },
      { type: 'visit', square: [ 29, 21 ] },
      { type: 'visit', square: [ 29, 22 ] },
      { type: 'visit', square: [ 29, 23 ] },
      { type: 'succeed', path: [
  [ 1, 3 ], [ 1, 4 ], [ 1, 5 ], [ 1, 6 ], [ 2, 6 ],
  [ 3, 6 ], [ 4, 6 ], [ 5, 6 ], [ 5, 7 ], [ 5, 8 ],
  [ 5, 9 ], [ 6, 9 ], [ 7, 9 ], [ 8, 9 ], [ 8, 10 ],
  [ 8, 11 ], [ 8, 12 ], [ 9, 12 ], [ 10, 12 ], [ 11, 12 ],
  [ 11, 11 ], [ 11, 10 ], [ 11, 9 ], [ 12, 9 ], [ 13, 9 ],
  [ 14, 9 ], [ 15, 9 ], [ 16, 9 ], [ 17, 9 ], [ 17, 10 ],
  [ 17, 11 ], [ 17, 12 ], [ 17, 13 ], [ 17, 14 ], [ 17, 15 ],
  [ 17, 16 ], [ 17, 17 ], [ 17, 18 ], [ 18, 18 ], [ 19, 18 ],
  [ 20, 18 ], [ 20, 17 ], [ 20, 16 ], [ 20, 15 ], [ 21, 15 ],
  [ 22, 15 ], [ 23, 15 ], [ 23, 16 ], [ 23, 17 ], [ 23, 18 ],
  [ 24, 18 ], [ 25, 18 ], [ 26, 18 ], [ 26, 17 ], [ 26, 16 ],
  [ 26, 15 ], [ 27, 15 ], [ 28, 15 ], [ 29, 15 ], [ 29, 16 ],
  [ 29, 17 ], [ 29, 18 ], [ 29, 19 ], [ 29, 20 ], [ 29, 21 ],
  [ 29, 22 ], [ 29, 23 ]
] }
    ]
  }
}
